package com.bookcyprus.webservicesV2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.2
 * 2022-05-30T12:59:13.807+05:30
 * Generated source version: 3.5.2
 *
 */
@WebServiceClient(name = "eBookingService",
                  wsdlLocation = "file:eBookingService.wsdl",
                  targetNamespace = "http://webservicesV2.bookcyprus.com/")
public class EBookingService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservicesV2.bookcyprus.com/", "eBookingService");
    public final static QName EBookingServiceSoap12 = new QName("http://webservicesV2.bookcyprus.com/", "eBookingServiceSoap12");
    public final static QName EBookingServiceSoap = new QName("http://webservicesV2.bookcyprus.com/", "eBookingServiceSoap");
    public final static QName EBookingServiceHttpPost = new QName("http://webservicesV2.bookcyprus.com/", "eBookingServiceHttpPost");
    static {
        URL url = null;
        try {
            url = new URL("file:eBookingService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EBookingService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:eBookingService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EBookingService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EBookingService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EBookingService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public EBookingService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public EBookingService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public EBookingService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns EBookingServiceSoap
     */
    @WebEndpoint(name = "eBookingServiceSoap12")
    public EBookingServiceSoap getEBookingServiceSoap12() {
        return super.getPort(EBookingServiceSoap12, EBookingServiceSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EBookingServiceSoap
     */
    @WebEndpoint(name = "eBookingServiceSoap12")
    public EBookingServiceSoap getEBookingServiceSoap12(WebServiceFeature... features) {
        return super.getPort(EBookingServiceSoap12, EBookingServiceSoap.class, features);
    }


    /**
     *
     * @return
     *     returns EBookingServiceSoap
     */
    @WebEndpoint(name = "eBookingServiceSoap")
    public EBookingServiceSoap getEBookingServiceSoap() {
        return super.getPort(EBookingServiceSoap, EBookingServiceSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EBookingServiceSoap
     */
    @WebEndpoint(name = "eBookingServiceSoap")
    public EBookingServiceSoap getEBookingServiceSoap(WebServiceFeature... features) {
        return super.getPort(EBookingServiceSoap, EBookingServiceSoap.class, features);
    }


    /**
     *
     * @return
     *     returns EBookingServiceHttpPost
     */
    @WebEndpoint(name = "eBookingServiceHttpPost")
    public EBookingServiceHttpPost getEBookingServiceHttpPost() {
        return super.getPort(EBookingServiceHttpPost, EBookingServiceHttpPost.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EBookingServiceHttpPost
     */
    @WebEndpoint(name = "eBookingServiceHttpPost")
    public EBookingServiceHttpPost getEBookingServiceHttpPost(WebServiceFeature... features) {
        return super.getPort(EBookingServiceHttpPost, EBookingServiceHttpPost.class, features);
    }

}
