package com.bookcyprus.webservicesV2;

import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.5.2
 * 2022-05-30T12:59:13.804+05:30
 * Generated source version: 3.5.2
 *
 */
@WebService(targetNamespace = "http://webservicesV2.bookcyprus.com/", name = "eBookingServiceHttpPost")
@XmlSeeAlso({ObjectFactory.class})
public interface EBookingServiceHttpPost {
}
