
package com.bookcyprus.webservicesV2;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.5.2
 * 2022-05-30T12:59:13.791+05:30
 * Generated source version: 3.5.2
 *
 */
public final class EBookingServiceHttpPost_EBookingServiceHttpPost_Client {

    private static final QName SERVICE_NAME = new QName("http://webservicesV2.bookcyprus.com/", "eBookingService");

    private EBookingServiceHttpPost_EBookingServiceHttpPost_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = EBookingService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        EBookingService ss = new EBookingService(wsdlURL, SERVICE_NAME);
        EBookingServiceHttpPost port = ss.getEBookingServiceHttpPost();


        System.exit(0);
    }

}
